name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./packages/browser-extension

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build browser extension
        working-directory: ./packages/browser-extension
        run: npm run build

      - name: Build CLI
        working-directory: ./packages/cli
        run: npm run build

      - name: Build cors-auth-middleware
        working-directory: ./packages/cors-auth-middleware
        run: npx run build

      - name: Typecheck
        run: npx tsc

      - name: Run JS test suite
        working-directory: ./packages/common/src
        run: npm run test
