name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./packages/browser-extension

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build browser extension
        working-directory: ./packages/browser-extension
        run: |
          cp config.example config.ts
          npm run build

      - name: Build CLI
        working-directory: ./packages/cli
        run: npm run build

      - name: Build cors-auth-middleware
        working-directory: ./packages/cors-auth-middleware
        run: |
          cp example.env.local .env.local
          npm ci
          npm run build

      - name: Typecheck
        run: npx tsc

      - name: Run JS test suite
        run: npm test
